useHotel-backend
Shreyas2121/useHotel-backend pull request #1
Opened 2022-10-25 07:39 UTC by Shreyas2121

2022-10-25 12:18 UTC, immy458 requested changes
The MVC software design pattern is not adequately followed. Take a look at the file structure below and and follow the same.
![image](https://user-images.githubusercontent.com/59685135/197770195-fad1b979-66c5-4190-acef-0b1102040217.png)

If your code is in MVC structure, it will be easier to add features in the future because it will be more organized, maintainable, reusable and flexible.

I think wherever needed we can have `max_length `parameter for `StringField `Datatype.

Use PascalCase naming convention to name all the model files

2022-10-25 12:18 UTC, immy458 commented on .gitignore
> +tests
Why are we not pushing the tests folder?

2022-10-25 12:18 UTC, immy458 commented on db_connect.py
> +    db_url = "mongodb+srv://shreyas:shreyas@project.kxd4hqz.mongodb.net/?retryWrites=true&w=majority"
Rename the db_url to db_connection_uri
Make a `.env` file, put the connection string in it, and use it here.

2022-10-25 12:18 UTC, immy458 commented on db_connect.py
> +def connection_db():
Rename the file to db_connection.py
Rename the `connection_db` method to `db_connect`

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +from db_connect import connection_db
Use PascalCase naming convention to name all the model files

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    booking_username = db.StringField()
rename username to name

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +class BookingRoom(db.Document):
remove the word 'booking' from every field

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    booking_useremail = db.EmailField()
rename useremail to email

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    booking_date = db.StringField()
change the data type to `DateTimeField()`

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    booking_check_in  = db.DateTimeField()
rename to `check_in_date` and change the data type to `DateField`

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    booking_check_out = db.DateTimeField()
rename to` check_out_date` and change the data type to` DateField`

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    booking_no_of_rooms = db.IntField(default=1)
rename this to 'num_of_rooms'

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    booking_addOns = db.DictField(field=db.IntField())
rename `addOns` to `add_ons`

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    booking_coupon_discount = db.StringField(default="")
rename `coupon_discount` to `coupon_discount_percentage` and  change data type to `IntField`

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +    def to_json(self):
Update these fields accordingly

2022-10-25 12:18 UTC, immy458 commented on models/coupon.py
> +class Coupon(db.Document):
I think it's better to create a separate object for each coupon with fields as
```
{
_id:  'someid'
code: 'somecode'
discount_percentage: 'percentage_value_in_int'
}
```

Reference this document then in the 'booking_room' and 'booking_hall' models to store the coupon details as:
```
class BookingRoom(db.Document):
    ...
    coupon = db.EmbeddedDocumentField(Coupon)
```

2022-10-25 12:18 UTC, immy458 commented on models/booking_hall.py
> +class BookingHall(db.Document):
Make the same changes that were suggested in the BookingRoom model.

2022-10-25 12:18 UTC, immy458 commented on models/hall.py
> +class Hall(db.Document):
Remove the word `hall `from every field

2022-10-25 12:18 UTC, immy458 commented on models/hall.py
> +    hall_type = db.StringField(requird=True)
isn't it `required`?

2022-10-25 12:18 UTC, immy458 commented on models/hall.py
> +    hall_image = db.ListField(db.StringField(),requird=True)
rename `image `to `images`

2022-10-25 12:18 UTC, immy458 commented on models/hall.py
> +    hall_max_occ = db.IntField(requird=True)
`max_guests` would be a better name for this.

2022-10-25 12:18 UTC, immy458 commented on models/room.py
> +class Room(db.Document):
Remove the word `room `from every fields

2022-10-25 12:18 UTC, immy458 commented on models/room.py
> +            "room_amenties": self.room_amenities,
Rename `amenties` to `amenities`

2022-10-25 12:18 UTC, immy458 commented on models/room.py
> +    room_max_occ = db.IntField(requird=True)
`max_occ` is not a very logical field name in my opinion, therefore please name it something more descriptive.

2022-10-25 12:18 UTC, immy458 commented on models/room.py
> +    room_id = db.IntField()
Do we need this field?

2022-10-25 12:18 UTC, immy458 commented on models/room.py
> +    room_discount = db.IntField(default=0)
This field can be deleted because I don't believe we are using it anywhere.

2022-10-25 12:18 UTC, immy458 commented on models/room.py
> +    room_area = db.StringField(requird=True)
Rename this field to `area_sq_ft `and change the datatype to `FloatField `or `IntField`

2022-10-25 12:18 UTC, immy458 commented on models/room.py
> +    room_type = db.StringField(requird=True)
isn't it `required`?

2022-10-25 12:18 UTC, immy458 commented on models/reviews.py
> +from db_connect import connection_db
Rename the file name to Review

2022-10-25 12:18 UTC, immy458 commented on models/reviews.py
> +class Reviews(db.Document):
Rename the class name to `Review`

2022-10-25 12:18 UTC, immy458 commented on models/reviews.py
> +    email = db.StringField()
Change the datatype for this field to `EmailField`

2022-10-25 12:18 UTC, immy458 commented on models/booking_room.py
> +            "_id":str(self.pk),
Update the below fields accordingly

2022-10-26 21:08 UTC, immy458 requested changes
Remove the commented codes and print statements
Better to have `_controller ` term for all the controller methods

2022-10-26 21:08 UTC, immy458 commented on .gitignore
> +tests
Why is this still here?

2022-10-26 21:08 UTC, immy458 commented on models/Coupon.py
> +            "_id": str(self.id),
I think this should be` self.pk`?

2022-10-26 21:08 UTC, immy458 commented on routes/addons_route.py
> +@addons_route.route('/addon/create', methods=['POST'])
Since the HTTP request is POST, we can delete the `/create` from the route because it is clear that it will create an addon.

2022-10-26 21:08 UTC, immy458 commented on routes/addons_route.py
> +    return create_addons()
Rename this to `create_addon_controller()`

2022-10-26 21:08 UTC, immy458 commented on application.py
> +application.register_blueprint(rooms_route)
I think we can have` url_prefix` property here with value as ` "/api"` for all the blueprints

2022-10-26 21:08 UTC, immy458 commented on application.py
> +def index():
We can do away with this method

2022-10-26 21:08 UTC, immy458 commented on routes/addons_route.py
> +@addons_route.route('/booking/addon',methods=['GET'])
Why do we have `/booking` if this is an addon route?
I believe we should keep it to `/addon` only
Leave space after comma (between method parameters)

2022-10-26 21:08 UTC, immy458 commented on routes/addons_route.py
> +def route_index():
Rename this to `get_addons()`

2022-10-26 21:08 UTC, immy458 commented on routes/addons_route.py
> +    return get_addons_data()
Since this a controller method we can rename this to` get_addons_controller`

2022-10-26 21:08 UTC, immy458 commented on controller/addon_controller.py
> +    return addon_service.service_create_addon()
The term `service_ ` can either be removed or added at the end.

2022-10-26 21:08 UTC, immy458 commented on controller/addon_controller.py
> +    return addon_service.service_get_addons_data()
rename this to `get_addons()`

2022-10-26 21:08 UTC, immy458 commented on services/addon_service.py
> +    return addonObj.to_json()
I think it should return Response Object  with status code 201 and not the created data
return `Response("Addon created", 201, mimetype='application/json')`
Read about response object

2022-10-26 21:08 UTC, immy458 commented on services/addon_service.py
> +    addonObj = AddOns .objects()
Remove the space

2022-10-26 21:08 UTC, immy458 commented on routes/booking_hall_route.py
> +def route_index():
rename this method to` book_hall()`

2022-10-26 21:08 UTC, immy458 commented on routes/booking_hall_route.py
> +    return book_hall()
rename this to `book_hall_contoller()`

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +        booking_username = data['name'],
Change these fields as per the model fields
Give more descriptive names for the fields in request body

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +    return jsonify({"message":"Booking Successful"})
This should return Response Object with status code

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +# def check_bookings():
The commented code can be removed

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +def service_check_bookings():
change this function name as it returns the number of halls available for each hall type

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +    parsed_check_in = parser.isoparse(checkin)
Here we can directly use the checkin date from data object, and get rid of the variable `checkin `since we don't use it anywhere else

2022-10-26 21:08 UTC, immy458 commented on models/BookingHall.py
> +    check_in_date = db.DateTimeField(required=True)
Since this is not a reservation for a room, I believe the `check_in_date `and `check_out_date `fields should be changed to `from_date` and `to_date`.
Update these field wherever it is used

2022-10-26 21:08 UTC, immy458 commented on services/booking_room_service.py
> +    booking_obj2 = BookingRoom.objects(booking_check_in__lt=parsed_check_out, booking_check_out__gte=parsed_check_out,)
The variable names `booking_obj  ` and  `booking_obj2 ` are not very meaningful, change it to something more descriptive

2022-10-26 21:08 UTC, immy458 commented on services/booking_room_service.py
> +
Change these variables name too

2022-10-26 21:08 UTC, immy458 commented on services/booking_room_service.py
> +            booking_data.append(i)
you can use extend method here, see the code below
```
data=[{'s':'d'},{'s1':'d'}, {'s':'d'}]
data2=[]
data2.extend(x for x in data if x not in data2 )
```

2022-10-26 21:08 UTC, immy458 commented on services/booking_room_service.py
> +    res = requests.get('http://usehotelbackend-env.eba-x3zhkiev.ap-northeast-1.elasticbeanstalk.com/booking/room/getDetails')
We can directly use the service method here

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +    booking_obj2 = BookingHall.objects(booking_check_in__lte=parsed_check_out, booking_check_out__gte=parsed_check_out,)
The variable names `booking_obj1 `and `booking_obj2 `are not very meaningful, change it to something more descriptive.
I think `booking_check_in__lte ` should be ` check_in_date__lte `

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +
Rename these field too

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +    res = requests.get('http://usehotelbackend-env.eba-x3zhkiev.ap-northeast-1.elasticbeanstalk.com/booking/hall/getDetails')
Why are we making a separate network call here? We can directly use the service method here
Rename res to `all_halls` or something more meaningful

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +    available_halls = {}
I think this should be renamed to `hall_inventory `?
Create a new object `halls_available ` to store the final output

2022-10-26 21:08 UTC, immy458 commented on services/booking_hall_service.py
> +    new={}
What is  `new`?

2022-10-26 21:08 UTC, immy458 commented on routes/booking_hall_route.py
> +@booking_hall_route.route('/booking/hall/check',methods=['POST'])
This should in the halls_route.py file with the end point as `hall/availability`

2022-10-26 21:08 UTC, immy458 commented on routes/booking_hall_route.py
> +    return check_booking_hall()
Should be renamed to `get_halls_availability_controller`

2022-10-26 21:08 UTC, immy458 commented on routes/booking_hall_route.py
> +def route_check():
Should be renamed to get_halls_availability

2022-10-26 21:08 UTC, immy458 commented on routes/booking_room_route.py
> +@booking_route.route('/booking/room/get', methods=['GET'])
remove ` /get ` since we already know this is a GET request

2022-10-26 21:08 UTC, immy458 commented on routes/booking_room_route.py
> +from flask import Blueprint
Implement the same changes that  were suggested in the booking_hall_route

2022-10-26 21:08 UTC, immy458 commented on controller/booking_hall_controller.py
> +def check_booking_hall():
This functions should be moved to halls_controller.py, with the name as ` get_halls_availability_controller`

2022-10-26 21:08 UTC, immy458 commented on routes/booking_room_route.py
> +@booking_route.route('/booking/room/check', methods=['POST'])
Move this to `rooms_route.py` file

2022-10-26 21:08 UTC, immy458 commented on controller/booking_room_controller.py
> +from services import booking_room_service
Implement the same changes that were suggested in `booking_hall_controllery.py`

2022-10-26 21:08 UTC, immy458 commented on services/booking_room_service.py
> +from datetime import date
Implement the same changes that were suggested in booking_hall_service.py

2022-10-26 21:08 UTC, immy458 commented on routes/cancelling_hall_route.py
> +from flask import Blueprint
This comes under the booking_hall_route.py, because here we are modifying the BookingHall collection.
Endpoint for it will be:
To Delete: `/booking/hall/<string:_id>`
To Get Booking By Email: `/booking/hall/<string:email>`

Change the method name `cancel_hall_booking `to `delete_booking`

2022-10-26 21:08 UTC, immy458 commented on controller/cancelling_hall_controller.py
> +from services import cancelling_hall_service
move this code to `booking_hall_controller.py`

2022-10-26 21:08 UTC, immy458 commented on services/cancelling_hall_service.py
> +    return booking.to_json()
After deleteing the record, it should return response object.
`Response("Hall Booking Deleted", status=200, mimetype='application/json')`

2022-10-26 21:08 UTC, immy458 commented on services/cancelling_hall_service.py
> +    bookings = BookingHall.objects().filter(booking_useremail=email)
`booking_useremail `should be changed to `email` as per the model

2022-10-26 21:08 UTC, immy458 commented on routes/cancelling_room_route.py
> +from flask import Blueprint
This comes under the booking_room_route.py, because here we are modifying the BookingRoom collection.
Endpoint for it will be:
To Delete: /booking/room/<string:_id>
To Get Booking By Email: /booking/room/<string:email>

Change the method name cancel_room_booking to delete_booking

2022-10-26 21:08 UTC, immy458 commented on services/cancelling_room_service.py
> +from models.BookingRoom import BookingRoom
Implement same changes that were suggested in cancelling_hall_service.py

2022-10-26 21:08 UTC, immy458 commented on services/cancelling_hall_service.py
> +from typing import Any
move this code to booking_hall_service.py

2022-10-26 21:08 UTC, immy458 commented on routes/coupon_route.py
> +@coupons_route.route('/coupons/create', methods=['POST'])
Remove the word `/create`

2022-10-26 21:08 UTC, immy458 commented on routes/coupon_route.py
> +    return create_coupon()
change this method name to `create_coupon_controller`

2022-10-26 21:08 UTC, immy458 commented on routes/coupon_route.py
> +def route_create_coupon():
change this method name to `create_coupon`

2022-10-26 21:08 UTC, immy458 commented on routes/coupon_route.py
> +@coupons_route.route('/booking/coupon/get',methods=['GET'])
Change this endpoint to `'/coupons'`

2022-10-26 21:08 UTC, immy458 commented on routes/coupon_route.py
> +@coupons_route.route('/booking/coupon',methods=['POST'])
Change this endpoint to '/coupon/validate'

2022-10-26 21:08 UTC, immy458 commented on routes/coupon_route.py
> +    return check_coupon()
change this method to validate_coupon_controller

2022-10-26 21:08 UTC, immy458 commented on services/coupon_service.py
> +    coupon_res = request.get_json()['coupon']
`coupon_code` would be a more appropriate name for `coupon_res `, Also change the `coupon `field from request object to `coupon_code`

2022-10-26 21:08 UTC, immy458 commented on services/coupon_service.py
> +    discount_res = request.get_json()['discount']
what is `discount_res`?

2022-10-26 21:08 UTC, immy458 commented on services/coupon_service.py
> +    return jsonify({'coupon': coupon.to_json()})
Better to return response object

2022-10-26 21:08 UTC, immy458 commented on services/coupon_service.py
> +        return "Invalid Coupon"
return response object with appropriate message and  status code 400

2022-10-26 21:08 UTC, immy458 commented on services/coupon_service.py
> +        return jsonify(couponObj[0].discount_percentage)
Better to return the full object?

2022-10-26 21:08 UTC, immy458 commented on routes/halls_route.py
> +@halls_route.route('/booking/hall/post',methods=['POST'])
Why do we have have` '/booking' ` in the endpoint? Isn't this just about the hall?

2022-10-26 21:08 UTC, immy458 commented on routes/halls_route.py
> +@halls_route.route('/booking/hall/getDetails',methods=['GET'])
Why do we have have'/booking' in the endpoint?

2022-10-26 21:08 UTC, immy458 commented on routes/rooms_route.py
> +@rooms_route.route('/room/create', methods=['POST'])
Remove the word '/create'

2022-10-26 21:08 UTC, immy458 commented on routes/rooms_route.py
> +@rooms_route.route('/booking/room/getDetails',methods=['GET'])
Why do we have have'/booking' in the endpoint?

2022-10-26 21:08 UTC, immy458 commented on routes/rooms_route.py
> +    return get_rooms_list()
Change this method to `get_rooms_controller`

2022-10-26 21:08 UTC, immy458 commented on services/hall_service.py
> +    return jsonify({'hall': hall.to_json()})
Should return response object

2022-10-26 21:08 UTC, immy458 commented on services/rooms_service.py
> +    return jsonify({'room': room.to_json()})
Should return response object

2022-10-26 21:08 UTC, immy458 commented on routes/reviews_route.py
> +@reviews_route.route('/reviews/',methods=['GET'])
remove the extra '/ ' from the endpoint

2022-10-26 21:08 UTC, immy458 commented on routes/reviews_route.py
> +def route_get():
change this method name

2022-10-26 21:08 UTC, immy458 commented on routes/reviews_route.py
> +    return add_reviews()
change this method name to add_review_controller

2022-10-26 21:08 UTC, immy458 commented on routes/reviews_route.py
> +    return get_top_reviews()
change this method name to get_top_reviews_controller

2022-10-26 21:08 UTC, immy458 commented on services/reviews_service.py
> +    return jsonify({"message":"Review Added"})
Return response object with status code and message

2022-10-26 21:08 UTC, immy458 commented on services/reviews_service.py
> +    review_data = Review.objects(rating__gte=5)  # type: ignore
why `__gte` shouldn't just be `=`

2022-10-27 05:37 UTC, Gekky-Pro-grammer commented on routes/reviews_route.py
> +@reviews_route.route('/reviews/',methods=['GET'])
done!

2022-10-27 06:11 UTC, Gekky-Pro-grammer commented on services/reviews_service.py
> +    return jsonify({"message":"Review Added"})
done!

2023-02-06 04:26 UTC, closed without merging